#!/bin/bash
# Radio Swiss Classic-Playlist
# $1 = outfile

### Variabel
Name="Radio Swiss Classic [www.radioswissclassic.ch]"
### 

# get...
wget -q --tries=2 --timeout=5 -O /tmp/playlist "http://www.radioswissclassic.ch/cgi-bin/pip/html.cgi?m=playlist&lang=de&v=d&loaded=#onair"

# Artist/Title
all=`grep -A2 'class="on"' /tmp/playlist`
artist=${all/*$';">'/}; artist=${artist/$'<'\/'strong>'*/}
title=${all/*$'strong><br '\/'>'/}; title=${title/$'<'\/'a><'\/'td>'*/}
# temp. no Info
artist=${artist:='---'}; titel=${title:='---'}

# write...
if [ $1 ]; then
	echo $Name    > $1
	echo $artist >> $1
	echo $title  >> $1
else
	echo "$Name: Interpret/Titel =  $artist / $title"
fi
