#
# defaut sysconfig for Reel NetClient
# (c) 2005 by Ralf Dotzert and MiniVDR.de
# (c) 2006-10 by Reel-Multimedia.com
#

DOMAIN="local"
DS_ENABLE="yes"
DS_TIMEOUT="2"
ETH0="yes"
ETH0_BRIDGE="-"
ETH0_USE_DHCP="yes"
ETH1="no"
ETH2="no"
GATEWAY=""
HOSTNAME="ReelNetClient"
MEDIADEVICE=""
MEDIADEVICE_ONLY_RECORDING="no"
NAMESERVER=""
UPDATECHECK_ENABLE="no"
UPNP_ENABLE="no"
USE_PROXY="no"
USE_UDP_REMOTE="yes"
USE_UDP_REMOTE_PORT="2003"
VLAN="no"
WOL_ENABLE="yes"
ZONEINFO="Europe/Berlin"
